export { AboutPage } from './about'
export { ContactPage } from './contact'
export { HomePage } from './home'
export { NotFoundPage } from './not-found'
export { ProjectsPage } from './projects'
export { ValuesPage } from './values'
